title: Software, Tech and Product.
subtitle: Make It Run → Make it Fast → Make it Beautiful
email: vaid.abhi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science Enthusiast. Programmer. Eternally Curious Person. Motion Picture Admirer. Amateur Gamer. Ex Co-Founder of a tech Startup. Rational. Humanist.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vaidabhishek
github_username: abhishekvaid

markdown: kramdown

repository: "mmistakes/minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: ["_pages"]

collections:
  posts:
    output: true